spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio_user
    password: portfolio_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        'format_sql': true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    'org.springframework': INFO
    'com.asierpc': DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: http://localhost:4200

jwt:
  secret: 2b7e151628aed2a6abf7158809cf4f3c7e8f8a8d6c3b4e2f1a9c7b6e5d4c3a2b
